title: lama小站
subtitle: 记录与分享
description: lama的小站 · 文章、笔记与资料分享
url: "https://lllllllama.me"
baseurl: ""

author:
  name: lllllllama
  email: you@example.com
  url: https://github.com/yourname

lang: zh-CN
timezone: Asia/Shanghai
permalink: /:categories/:year/:month/:day/:title/

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

nav:
  - title: 首页
    url: /
  - title: 关于
    url: /pages/about/
  - title: 归档
    url: /pages/archives/
  - title: 标签
    url: /pages/tags/
  - title: RSS
    url: /feed.xml
  - title: 管理
    url: /admin/

social:
  github: lllllllama
  twitter: yourhandle
  weibo: yourweibo
  rss: /feed.xml

appearance:
  default_theme: cyber-cyan
  enable_theme_switcher: true
  reduce_motion_respect: true

exclude:
  - vendor
  - node_modules
  - scripts
  - README_local.md
  - Gemfile.lock
  - .github

features:
  search: true
  toc: true
  comments:
    giscus:
      enabled: false
      repo: ""
      repo_id: ""
      category: "General"
      category_id: ""
      mapping: pathname
      reactions_enabled: 1
      emit_metadata: 0
      input_position: bottom
      theme: dark
      lang: zh-CN

search_index:
  path: /search.json
