publish_mode: editorial_workflow
open_authoring: true

backend:
  name: github
  repo: lllllllama/blog_web
  branch: main
  base_url: https://netlify-cms-github-oauth-provider-g9fh.onrender.com

# 本地开发可启用本地后端，无需登录（仅本地有效）
local_backend: true

site_url: https://lllllllama.me
logo_url: /assets/img/logo.svg

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: posts
    label: 文章
    label_singular: 文章
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: frontmatter
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 日期, name: date, widget: datetime, format: "yyyy-MM-dd HH:mm:ss", time_format: "HH:mm" }
      - { label: 分类, name: categories, widget: list, default: ["blog"] }
      - { label: 标签, name: tags, widget: list, required: false }
      - { label: 置顶, name: pin, widget: boolean, default: false, required: false }
      - { label: 封面, name: cover, widget: image, required: false }
      - { label: 摘要, name: description, widget: text, required: false }
      - { label: 正文, name: body, widget: markdown }
      - label: 图片集
        name: gallery
        widget: list
        required: false
        summary: "{{fields.image}}"
        fields:
          - { label: 图片, name: image, widget: image }
          - { label: 说明, name: caption, widget: string, required: false }
      - label: 附件（PDF/其它文件）
        name: attachments
        widget: list
        required: false
        fields:
          - label: 文件
            name: file
            widget: file
            media_folder: "assets/files"
            public_folder: "/assets/files"
            # 仅提示：可上传 pdf/zip 等；如需强校验可加 pattern
          - { label: 内嵌预览, name: embed, widget: boolean, default: true, required: false }
          - { label: 标题, name: title, widget: string, required: false }

  - name: pages
    label: 页面
    files:
      - label: 关于
        name: about
        file: pages/about.md
        fields:
          - { label: 标题, name: title, widget: string }
          - { label: 正文, name: body, widget: markdown }
      - label: 归档
        name: archives
        file: pages/archives.md
        fields:
          - { label: 标题, name: title, widget: string }
          - { label: 正文, name: body, widget: markdown }
